### PR TITLE
Remove TokenType, literal field is redundant

### PR DESCRIPTION
**Pull request by chr4**

### CODE REVIEW

**Comment by chr4** [comment]
As soon as I introduce Indent(String) and Integer(i64), I'm getting the following error. Apparently, match only works when all enum items are of the same type or so?

```
error[E0308]: match arms have incompatible types
  --> src/token.rs:49:15
   |
49 |     let tok = match ident {
   |               ^ expected enum `token::Token`, found fn item
   |
   = note: expected type `token::Token`
   = note:    found type `fn(std::string::String) -> token::Token {token::Token::Ident}`
note: match arm with an incompatible type
```

Hints apprechiated. When just using Ident and Integer, the tests run through, though, which is bad. This is because I don't check for the literal anymore at all...

**Comment by dnseitz** [comment]
Match should work for all enum types as long as you cover every case. The issue it looks like you're running into is the type that the match expression evaluates to. The compiler is expecting the type returned from the match to be `token::Token`, but it's finding a `fn(String) -> Token`. 

It's hard to say the exact problem without seeing each of the match arms but I'd guess that you're trying to use some function to parse the identifier into a token but just returning the function itself instead of calling it.

**Comment by chr4** [comment]
Thanks for the explanation!
The problem was, that I've tried to return `Token::Ident` from `match`, but `Token::Ident("string".to_string())` was required. I wasn't used to the error message, so it took a while till I understood what it meant.

**Comment by phrohdoh** [comment]
FYI `next_token_test`'s vec could just be `vec![ Token::Let, ... ]` instead of repeated `push`es.

**Comment by chr4** [comment]
Thanks @Phrohdoh! Fixed it!

**Comment by chr4** [comment]
Changing the `Lexer` struct was heavily inspired by @JayKickliter (Thanks!).
You can find his implementation here: https://github.com/JayKickliter/monkey/blob/master/src/lexer/mod.rs

**Pull request merged**
