### PR TITLE
Use char::is_numeric instead of hand-rolled is_digit

### PR DESCRIPTION
**Pull request by phrohdoh**

### CODE REVIEW

**Comment by chr4** [comment]
Thanks!
I suppose the `is_letter` function can also be replaced/ improved using `char::is_alphabetic`?

```rust
fn is_letter(ch: char) -> bool {
    ch.is_alphabetic() || ch == '_'
}
```

what do you think? I couldn't find a `char::` method that checks for alphabetic + underscore.

**Comment by phrohdoh** [comment]
Right, I was going to do that too but forgot about `is_alphabetic`. I can include that in this PR or a separate one, your choice. :-)

**Comment by chr4** [comment]
Feel free to just push it to into this pull-request, too.

**Comment by phrohdoh** [comment]
Done!

**Comment by chr4** [comment]
Thanks!

**Pull request merged**
